/**:
  ros__parameters:
    video_device: "/dev/v4l/by-path/platform-3610000.usb-usb-0:1.1:1.0-video-index0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera_f/camera_link"
    pixel_format: "mjpeg2rgb"
    image_width: 640
    image_height: 480
    camera_name: "camera_f"
    camera_info_url: "file:///home/ace428/autoware.agv428/src/sensor_component/external/usb_cam/config/camera_info_f.yaml"

