/**:
  ros__parameters:
    video_device: "/dev/v4l/by-path/platform-3610000.usb-usb-0:4.4:1.0-video-index0"   
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera_b/camera_link"
    pixel_format: "mjpeg2rgb"
    image_width: 1920
    image_height: 1080
    camera_name: "camera_b"
    camera_info_url: "file:///home/ace428/autoware.agv428/src/sensor_component/external/usb_cam/config/camera_info_b.yaml"

