planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.25
      allow_unknown: false
      max_iterations: 10000000
      downsample_costmap: false
      downsampling_factor: 2             
      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 1.28
      reverse_penalty: 1.0
      analytic_expansion_max_length: 3.0
      cost_penalty: 2.0
      analytic_expansion_max_cost: 200.0
      use_quadratic_cost_penalty: false
      goal_heading_mode: "DEFAULT"
      cache_obstacle_heuristic: True
      smooth_path: true
      allow_primitive_interpolation: true
      angle_quantization_bins: 32
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"
      robot_base_frame: "base_link"
      footprint: "[[1.25, 0.36], [1.25, -0.36], [-1.2, -0.36], [-1.2, 0.36]]" 
      resolution: 0.05
      footprint_padding: 0.01
      update_frequency: 1.0
      publish_frequency: 1.0
      transform_tolerance: 0.5
      footprint_clearing_enabled: true
      always_send_full_costmap: true
      service_introspection_mode: "disabled"
      plugins: ["static_layer", "obstacle_layer", "denoise_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/map"
        subscribe_to_updates: true
        transform_tolerance: 0.1

        
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        observation_sources: "scan_front scan_livox"

        scan_front:
          topic: "/scan_front"
          data_type: "LaserScan"
          obstacle_min_range: 0.05
          obstacle_max_range: 12.0
          raytrace_min_range: 0.05
          raytrace_max_range: 12.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          inf_is_valid: true

        scan_livox:
          topic: "/scan_livox"
          data_type: "LaserScan"
          obstacle_min_range: 0.0
          obstacle_max_range: 70.0
          raytrace_min_range: 0.0
          raytrace_max_range: 70.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          inf_is_valid: true

      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 4
        group_connectivity_type: 4

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.7
        cost_scaling_factor: 4.6
        inflate_unknown: false
        
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"
      robot_base_frame: "base_link"
      footprint: "[[1.25, 0.36], [1.25, -0.36], [-1.2, -0.36], [-1.2, 0.36]]"
      rolling_window: true
      width: 14
      height: 14
      resolution: 0.05
      transform_tolerance: 0.5
      update_frequency: 10.0
      publish_frequency: 10.0
      service_introspection_mode: "disabled"
      footprint_padding: 0.01
      plugins: ["static_layer", "obstacle_layer", "denoise_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true
        map_topic: "/map"
        subscribe_to_updates: true
        footprint_clearing_enabled: true
        transform_tolerance: 0.1

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        footprint_clearing_enabled: true
        observation_sources: "scan_front scan_livox"

        scan_front:
          topic: "/scan_front"
          data_type: "LaserScan"
          obstacle_min_range: 0.05
          obstacle_max_range: 12.0
          raytrace_min_range: 0.05
          raytrace_max_range: 12.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          inf_is_valid: true

        scan_livox:
          topic: "/scan_livox"
          data_type: "LaserScan"
          obstacle_min_range: 0.0
          obstacle_max_range: 70.0
          raytrace_min_range: 0.0
          raytrace_max_range: 70.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          marking: true
          clearing: true
          inf_is_valid: true

      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 4
        group_connectivity_type: 4

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.7
        cost_scaling_factor: 4.6
        inflate_unknown: false
        inflate_around_unknown: false
        
        
controller_server:
  ros__parameters:
    odom_topic: "/odometry/filtered"
    use_sim_time: false
    controller_frequency: 30.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    controller_plugins: ["MPPI"]
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.15
      movement_time_allowance: 8.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.05
      stateful: true
    MPPI:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      iteration_count: 1
      prune_distance: 4.0
      transform_tolerance: 0.1
      temperature: 0.3
      gamma: 0.015
      motion_model: "Ackermann"
      visualize: false
      enforce_path_inversion: true
      inversion_xy_tolerance: 0.2
      inversion_yaw_tolerance: 0.4
      vx_std: 0.2
      vy_std: 0.2
      wz_std: 0.4
      vx_max: 0.7
      vx_min: -0.7
      vy_max: 0.0
      wz_max: 3.0
      ax_max: 3.0
      ax_min: -3.0
      ay_min: -3.0
      ay_max: 3.0
      az_max: 3.5
      AckermannConstraints:
        min_turning_r: 1.28
      TrajectoryVisualizer:
        trajectory_step: 5
        time_step: 3
      critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic","PathAngleCritic"]
      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 4.0
      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 1.4
      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5
      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.81
        critical_cost: 300.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2
      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.07
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: true
      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4
      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 0.6
        mode: 2


collision_monitor:
  ros__parameters:
    use_sim_time: false
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel"
    cmd_vel_out_topic: "cmd_vel_final"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    base_shift_correction: false
    enable_stamped_cmd_vel: false
    use_realtime_priority: false

    polygons: ["PolygonStop", "PolygonSlow", "FootprintApproach"]

    # 緊急停止區域 (前後左右各加 20cm)
    PolygonStop:
      type: "polygon"
      points: [1.45, 0.46, 1.45, -0.46, -1.4, -0.46, -1.4, 0.46]
      action_type: "stop"
      max_points: 3
      visualize: true
      polygon_pub_topic: "polygon_stop"

    # 減速區域 (比停止區域四周大 40cm)
    PolygonSlow:
      type: "polygon"
      points: [1.85, 0.61, 1.85, -0.61, -1.8, -0.61, -1.8, 0.61]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.3
      visualize: true
      polygon_pub_topic: "polygon_slowdown"

    # 動態預測區域 (強化邊界預測)
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 2.0
      simulation_time_step: 0.02
      max_points: 5
      visualize: true
      enabled: true

    observation_sources: ["scan_front", "scan_livox"]
    scan_front:
      type: "scan"
      topic: "/scan_front"

    scan_livox:
      type: "scan"
      topic: "/scan_livox"

          

behavior_server:
  ros__parameters:
    use_sim_time: false
    server_timeout: 20
    behavior_plugins: ["wait"]
    wait:
      plugin: "nav2_behaviors/Wait"
      wait_duration: 5.0
         
bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: "/home/ace428/amr/src/amr_navigation/behavior_trees/test.xml"
    default_nav_through_poses_bt_xml: "/home/ace428/amr/src/amr_navigation/behavior_trees/test.xml"
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odometry/filtered"
    transform_tolerance: 1.0
    goal_blackboard_id: "goal"
    goals_blackboard_id: "goals"
    bt_loop_duration: 100
    default_server_timeout: 20
    publish_behavior_tree: true

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: true
    loop_rate: 20
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - behavior_server
      - bt_navigator
      - waypoint_follower
      - collision_monitor
