docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    odom_topic: "/odometry/filtered"
    dock_backwards: true

    dock_database: /home/ace428/schedule/pallet_database.yaml
    dock_plugins: ['pallet_dock']
    pallet_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: 1.0
      use_external_detection_pose: true
      use_battery_status: false   # 關閉電池狀態檢查，相當於 NonCharging 模式
      external_detection_timeout: 1.0
      external_detection_translation_x: -0.40
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.4
      v_linear_max: 0.4
      use_collision_detection: true
      dock_collision_threshold: 0.5

