scan_front_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -1.2
        max_x: 1.25
        min_y: -0.36
        max_y: 0.36
        min_z: -1.0
        max_z: 2.0
        invert: false

scan_livox_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -1.2
        max_x: 1.25
        min_y: -0.36
        max_y: 0.36
        min_z: -1.0
        max_z: 2.0
        invert: false

