scan_front_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: 0.70
        max_x: 0.90
        min_y: -0.25
        max_y: 0.25
        min_z: -1.0
        max_z: 2.0
        invert: false

scan_rear_filter:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.39
        max_x: 1.25
        min_y: -0.36
        max_y: 0.36
        min_z: -1.0
        max_z: 2.0
        invert: false

