image_width: 1920
image_height: 1080
camera_name: camera_l
distortion_model: equidistant
camera_matrix:
  rows: 3
  cols: 3
  data: [548.4797, 0.0, 948.5973,
         0.0, 548.4797, 502.9120,
         0.0, 0.0, 1.0]
distortion_coefficients:
  rows: 1
  cols: 4
  data: [-9.4574e-04, 1.0291e-06, -1.4440e-09, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [548.4797, 0.0, 948.5973, 0.0,
         0.0, 548.4797, 502.9120, 0.0,
         0.0, 0.0, 1.0, 0.0]
